### ISSUE TITLE
didnt want to fork, but

### ISSUE THREAD

**Issue by YourSandwich** [czM1K3/ansible-arch-linux-base#1]
Thank you for your project i took a loot of inspiration of it. Now i am able to install arch linux with ansible in 1min!!! :DDD

Here is my aprouch with a varianty to format the partitions as btrfs with subvolumes to enable easy snapshoting

I learnd ansible and yaml in less then 5h thanks to you <3

Do with it whatever you want <3
[arch_kde_setup.txt](https://github.com/czM1K3/ansible-arch-linux-base/files/8485179/arch_kde_setup.txt)
[arch_packages.txt](https://github.com/czM1K3/ansible-arch-linux-base/files/8485180/arch_packages.txt)
[arch_pre_setup.txt](https://github.com/czM1K3/ansible-arch-linux-base/files/8497417/arch_pre_setup.txt)

**Comment by czM1K3** [comment]
Hi, thank you for your feedback. I'm planning to extend this for multiple filesystems and desktop environments, but currently, I'm really busy. But I will implement your code soon, I swear.

**Comment by YourSandwich** [comment]
<3
